server:
  port: 8090
#  servlet:
#    context-path: /aqs
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://localhost:3306/springdata?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  redis:
    database: 0
    host: 172.19.70.8
    port: 30139
    jedis:
      pool:
        max-active: 100 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制)
        max-idle: 100 #连接池中的最大空闲连接
        min-idle: 50 #连接池中的最小空闲连接
        timeout: 6000 #连接超时时间（毫秒）
  mvc: #加载thymeleaf后这个配置无效
    view:
      prefix: /pages/ #视图路径
      suffix: .html #视图后缀名
  #上传文件大小
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  #logback配置    
  logging:
    config: classpath:logback-spring.xml

  thymeleaf:
    prefix: classpath:/static/pages/ #如果没有配置，thymeleaf默认页面放在templates下

  swagger: #配置swagger是否开启
    enable: true

resourceLocations:
  uploadPath: D:/uploaded_files/ #文件上传路径
resourceHandler:
  pathHandler: /files/ #文件访问映射路径
tcp:
  date:
    patterns: yyyy-MM-dd HH:mm:ss,yyyy-MM-dd,yyyy-MM-dd HH:mm:ss.SSS